import {
  isWorkspaceFileSearchQuery,
  type WorkspaceFileCandidate,
} from "../shared/workspaceFileSearch";

export interface FileAutocompleteOptions {
  readonly input: HTMLInputElement;
  readonly onQuery: (query: string) => void;
  readonly onSelect?: (candidate: WorkspaceFileCandidate) => void;
  readonly debounceMs?: number;
}

let nextAutocompleteId = 0;

/**
 * The shared input-side controller for link and image file suggestions.
 * Discovery and ranking stay in the extension host; this class only owns the
 * small popup and the keyboard/focus contract around the input element.
 */
export class FileAutocomplete {
  private readonly input: HTMLInputElement;
  private readonly onQuery: (query: string) => void;
  private readonly onSelect:
    ((candidate: WorkspaceFileCandidate) => void) | undefined;
  private readonly debounceMs: number;
  private readonly popup: HTMLDivElement;
  private readonly inputHandler: () => void;
  private readonly keydownHandler: (event: KeyboardEvent) => void;
  private readonly pointerDownHandler: (event: PointerEvent) => void;
  private readonly clickHandler: (event: MouseEvent) => void;
  private queryTimer: ReturnType<typeof setTimeout> | undefined;
  private candidates: readonly WorkspaceFileCandidate[] = [];
  private activeIndex = -1;
  private enabled = false;
  private suppressSubmit = false;
  private suppressSubmitTimer: number | undefined;

  public constructor(options: FileAutocompleteOptions) {
    this.input = options.input;
    this.onQuery = options.onQuery;
    this.onSelect = options.onSelect;
    this.debounceMs = Math.max(0, Math.min(options.debounceMs ?? 75, 250));
    const ownerDocument = this.input.ownerDocument;
    this.popup = ownerDocument.createElement("div");
    this.popup.className = "mm-file-autocomplete";
    this.popup.id = `mm-file-autocomplete-${++nextAutocompleteId}`;
    this.popup.hidden = true;
    this.popup.setAttribute("role", "listbox");
    this.popup.setAttribute("aria-label", "Workspace files");
    this.input.setAttribute("role", "combobox");
    this.input.setAttribute("aria-autocomplete", "list");
    this.input.setAttribute("aria-controls", this.popup.id);
    this.input.setAttribute("aria-expanded", "false");
    this.input.autocomplete = "off";
    this.input.parentElement?.append(this.popup);

    this.inputHandler = () => this.handleInput();
    this.keydownHandler = (event) => this.handleKeyDown(event);
    this.pointerDownHandler = (event) => {
      const target = event.target;
      if (target instanceof Node && this.popup.contains(target))
        event.preventDefault();
    };
    this.clickHandler = (event) => this.handleClick(event);
    this.input.addEventListener("input", this.inputHandler);
    this.input.addEventListener("keydown", this.keydownHandler);
    this.popup.addEventListener("pointerdown", this.pointerDownHandler);
    this.popup.addEventListener("click", this.clickHandler);
  }

  public open(): void {
    this.enabled = true;
    this.clear();
  }

  public close(): void {
    this.enabled = false;
    this.clear();
    this.clearSubmitSuppression();
  }

  public clear(): void {
    if (this.queryTimer !== undefined) {
      clearTimeout(this.queryTimer);
      this.queryTimer = undefined;
    }
    this.candidates = [];
    this.activeIndex = -1;
    this.popup.replaceChildren();
    this.popup.hidden = true;
    this.input.setAttribute("aria-expanded", "false");
    this.input.removeAttribute("aria-activedescendant");
  }

  public setCandidates(candidates: readonly WorkspaceFileCandidate[]): void {
    if (!this.enabled || !isWorkspaceFileSearchQuery(this.input.value)) {
      this.clear();
      return;
    }
    this.candidates = candidates.slice(0, 10).filter(isSafeCandidate);
    this.activeIndex = this.candidates.length > 0 ? 0 : -1;
    this.render();
  }

  /** Consume the submit generated by a candidate-selection Enter key, once. */
  public consumeSubmit(): boolean {
    const suppressed = this.suppressSubmit;
    this.suppressSubmit = false;
    if (this.suppressSubmitTimer !== undefined) {
      clearTimeout(this.suppressSubmitTimer);
      this.suppressSubmitTimer = undefined;
    }
    return suppressed;
  }

  public dispose(): void {
    this.close();
    this.input.removeEventListener("input", this.inputHandler);
    this.input.removeEventListener("keydown", this.keydownHandler);
    this.popup.removeEventListener("pointerdown", this.pointerDownHandler);
    this.popup.removeEventListener("click", this.clickHandler);
    this.popup.remove();
  }

  private handleInput(): void {
    this.suppressSubmit = false;
    this.clear();
    if (!this.enabled || !isWorkspaceFileSearchQuery(this.input.value)) return;
    const query = this.input.value.trim();
    const schedule = (): void => {
      this.queryTimer = undefined;
      if (
        this.enabled &&
        query === this.input.value.trim() &&
        isWorkspaceFileSearchQuery(query)
      )
        this.onQuery(query);
    };
    if (this.debounceMs === 0) schedule();
    else this.queryTimer = setTimeout(schedule, this.debounceMs);
  }

  private handleKeyDown(event: KeyboardEvent): void {
    if (event.isComposing || event.keyCode === 229) return;
    const visible = !this.popup.hidden && this.candidates.length > 0;
    if (event.key === "Escape" && visible) {
      event.preventDefault();
      event.stopPropagation();
      this.clear();
      this.input.focus();
      return;
    }
    if (!visible) return;
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      event.preventDefault();
      event.stopPropagation();
      const delta = event.key === "ArrowDown" ? 1 : -1;
      this.activeIndex =
        (this.activeIndex + delta + this.candidates.length) %
        this.candidates.length;
      this.render();
      return;
    }
    if (
      event.key === "Enter" &&
      !event.ctrlKey &&
      !event.metaKey &&
      !event.altKey &&
      !event.shiftKey
    ) {
      const candidate = this.candidates[this.activeIndex];
      if (!candidate) return;
      event.preventDefault();
      event.stopPropagation();
      this.select(candidate, true);
    }
  }

  private handleClick(event: MouseEvent): void {
    const target = event.target;
    if (!(target instanceof Element)) return;
    const option = target.closest<HTMLButtonElement>(
      "[data-mm-file-autocomplete-option]",
    );
    if (!option) return;
    const index = Number(option.dataset.mmFileAutocompleteOption);
    const candidate = this.candidates[index];
    if (!candidate) return;
    event.preventDefault();
    this.select(candidate, false);
  }

  private select(
    candidate: WorkspaceFileCandidate,
    suppressSubmit: boolean,
  ): void {
    this.input.value = candidate.relativePath;
    this.clear();
    if (suppressSubmit) this.setSubmitSuppression();
    this.input.focus();
    this.onSelect?.(candidate);
  }

  private setSubmitSuppression(): void {
    this.clearSubmitSuppression();
    this.suppressSubmit = true;
    const ownerWindow = this.input.ownerDocument.defaultView;
    this.suppressSubmitTimer = ownerWindow?.setTimeout(() => {
      this.suppressSubmit = false;
      this.suppressSubmitTimer = undefined;
    }, 0);
  }

  private clearSubmitSuppression(): void {
    if (this.suppressSubmitTimer !== undefined) {
      clearTimeout(this.suppressSubmitTimer);
      this.suppressSubmitTimer = undefined;
    }
    this.suppressSubmit = false;
  }

  private render(): void {
    this.popup.replaceChildren();
    this.popup.hidden = this.candidates.length === 0;
    this.input.setAttribute("aria-expanded", String(!this.popup.hidden));
    this.input.removeAttribute("aria-activedescendant");
    if (this.popup.hidden) return;

    this.candidates.forEach((candidate, index) => {
      const option = this.input.ownerDocument.createElement("button");
      option.type = "button";
      option.className = "mm-file-autocomplete-option";
      option.dataset.mmFileAutocompleteOption = String(index);
      option.id = `${this.popup.id}-option-${index}`;
      option.setAttribute("role", "option");
      option.setAttribute("aria-selected", String(index === this.activeIndex));
      const name = this.input.ownerDocument.createElement("span");
      name.className = "mm-file-autocomplete-name";
      name.textContent = candidate.fileName;
      const directory = this.input.ownerDocument.createElement("span");
      directory.className = "mm-file-autocomplete-directory";
      directory.textContent = candidate.directory;
      option.append(name, directory);
      this.popup.append(option);
    });
    const active = this.popup.querySelector<HTMLButtonElement>(
      `[data-mm-file-autocomplete-option="${this.activeIndex}"]`,
    );
    if (active) {
      active.classList.add("is-active");
      this.input.setAttribute("aria-activedescendant", active.id);
      try {
        active.scrollIntoView({ block: "nearest" });
      } catch {
        // jsdom and older embedded WebViews may not implement scrollIntoView.
      }
    }
  }
}

function isSafeCandidate(
  candidate: WorkspaceFileCandidate,
): candidate is WorkspaceFileCandidate {
  return (
    candidate.fileName.length > 0 &&
    candidate.fileName.length <= 1_024 &&
    candidate.directory.length > 0 &&
    candidate.directory.length <= 8_192 &&
    candidate.relativePath.length > 0 &&
    candidate.relativePath.length <= 8_192 &&
    /^(?:\.\/|\.\.\/)/.test(candidate.relativePath) &&
    !hasControlCharacter(
      `${candidate.fileName}${candidate.directory}${candidate.relativePath}`,
    ) &&
    !candidate.fileName.includes("\\") &&
    !candidate.directory.includes("\\") &&
    !candidate.relativePath.includes("\\") &&
    !/[?#]/.test(candidate.relativePath)
  );
}

function hasControlCharacter(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code <= 0x1f || code === 0x7f) return true;
  }
  return false;
}
